
FROM library/python:3.9.13

RUN python -m pip install poetry
RUN poetry install


RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app
COPY ./ /usr/src/app
RUN make install
COPY ./utils/ /usr/src/utils
EXPOSE 80
ENV PYTHONUNBUFFERED=1

CMD ["sh", "./utils/run.sh"]

